name = "chat"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[assets]
directory = "public"
binding = "ASSETS"

# D1 Database binding
[[d1_databases]]
binding = "DB" # Worker에서 env.DB로 접근 가능
database_name = "chat-contexts"
database_id = "a41896bf-d115-4d65-aa9b-36213d77db77"
migrations_dir = "migrations"

# Environment variables
[vars]
# These will be available in production. For development, use .dev.vars file.
